const DRILL_MS_PER_UNIT = 450
const DEPLETED_ASTEROID_COLORS = {
  base: 0x636970,
  edge: 0x42464c,
  crater: 0x7a8088
}
const FRAGMENT_RADIUS = 10
const MEDIUM_RADIUS = 22
const SMALL_ASTEROID_RADIUS_MAX = FRAGMENT_RADIUS + 4
const MEDIUM_ASTEROID_RADIUS_MAX = MEDIUM_RADIUS + 6
const LARGE_RADIUS = 42
const HUGE_ASTEROID_RADIUS_MAX = 78
const MINING_LEVEL_SCALE_MAX = 24
const ASTEROID_SAFE_RADIUS = 180
const MOTHERSHIP_SAFE_RADIUS = 320
const MOTHERSHIP_FIELD_HEIGHT = 420
const DOCK_ARM_LENGTH = 61
const DOCK_ARM_HALF_HEIGHT = 11
const DOCK_ARM_HULL_NOTCH = 14
const DOCK_PORT_OUTSET = 8
const DOCK_PORT_FRAME_OFFSET = 16
const DOCK_PORT_FRAME_WIDTH = 17
const DOCK_PORT_FRAME_HEIGHT = 24
const MOTHERSHIP_SHIELD_RADIUS = 230
const SHIELD_HIT_COOLDOWN_MS = 450
const ASTEROID_COLLISION_FRACTURE_COOLDOWN_MS = 500
const ASTEROID_FRACTURE_IMPACT_SPEED_MIN = 45
const ASTEROID_SPAWN_SETTLE_MS = 1400
const ASTEROID_SPAWN_MIN_GAP = 24
const HUGE_ASTEROID_FRACTURE_IMPACT_MIN = 95
const ASTEROID_FIELD_MAX_COUNT = 64
const SHIELD_REPEL_SPEED_MIN = 130
const SHIELD_REPEL_SPEED_MAX = 220
const PIXELS_PER_METER = 4
const DOCK_AUTO_METERS = 5
const DOCK_AUTO_DISTANCE_PX = DOCK_AUTO_METERS * PIXELS_PER_METER
const DOCK_ARRIVAL_METERS = DOCK_AUTO_METERS

export {
  DRILL_MS_PER_UNIT,
  DEPLETED_ASTEROID_COLORS,
  FRAGMENT_RADIUS,
  MEDIUM_RADIUS,
  SMALL_ASTEROID_RADIUS_MAX,
  MEDIUM_ASTEROID_RADIUS_MAX,
  LARGE_RADIUS,
  HUGE_ASTEROID_RADIUS_MAX,
  MINING_LEVEL_SCALE_MAX,
  ASTEROID_SAFE_RADIUS,
  MOTHERSHIP_SAFE_RADIUS,
  MOTHERSHIP_FIELD_HEIGHT,
  DOCK_ARM_LENGTH,
  DOCK_ARM_HALF_HEIGHT,
  DOCK_ARM_HULL_NOTCH,
  DOCK_PORT_OUTSET,
  DOCK_PORT_FRAME_OFFSET,
  DOCK_PORT_FRAME_WIDTH,
  DOCK_PORT_FRAME_HEIGHT,
  MOTHERSHIP_SHIELD_RADIUS,
  SHIELD_HIT_COOLDOWN_MS,
  ASTEROID_COLLISION_FRACTURE_COOLDOWN_MS,
  ASTEROID_FRACTURE_IMPACT_SPEED_MIN,
  ASTEROID_SPAWN_SETTLE_MS,
  ASTEROID_SPAWN_MIN_GAP,
  HUGE_ASTEROID_FRACTURE_IMPACT_MIN,
  ASTEROID_FIELD_MAX_COUNT,
  SHIELD_REPEL_SPEED_MIN,
  SHIELD_REPEL_SPEED_MAX,
  PIXELS_PER_METER,
  DOCK_AUTO_METERS,
  DOCK_AUTO_DISTANCE_PX,
  DOCK_ARRIVAL_METERS
}
