const WORLD_SCALE = 3
const PLAYER_MAX_SPEED = 220
const PLAYER_ROT_SPEED = 2.8
const GRAPPLE_SPEED = 460
const GRAPPLE_COOLDOWN_MS = 350
const GRAPPLE_MAX_RANGE = 360
const GRAPPLE_PULL_SPEED = 300
const GRAPPLE_ATTACH_DISTANCE = 14
const GRAPPLE_SOFT_DOCK_SPEED_MAX = 85
const GRAPPLE_DOCK_ASSIST_RADIUS = 300
const GRAPPLE_DOCK_DAMP_RATE = 5.5
const GRAPPLE_DOCK_STEER_ACCEL = 34
const GRAPPLE_RIDE_MIN_DAMAGE_SCALE = 0.15
const GRAPPLE_SOFT_COLLISION_SMOOTHING = 0.55
const ATTACH_RELEASE_REVERSE_BOOST = 2
const GRAPPLE_DETACH_GRACE_MS = 650
const PLAYER_FUEL_MAX_DEFAULT = 500
const FUEL_BURN_PER_SEC = 9
const FUEL_LOW_THRESHOLD = 125
const FUEL_LOST_GRACE_MS = 15000
const FUEL_RESCUE_MIN_CLOSURE_SPEED = 12
const FUEL_RESCUE_FULL_PAUSE_CLOSURE_SPEED = 55
const FUEL_RESCUE_GRACE_DECAY_MIN = 0.08
const EMERGENCY_THRUST_MULT = 0.38
const BATTERY_DRAIN_EMERGENCY_THRUST_PER_SEC = 24
const DISTRESS_TOW_STEER_ACCEL = 28
const DISTRESS_TOW_DAMP_RATE = 3
const BATTERY_LOW_THRESHOLD = 20
const BATTERY_DRAIN_GRAPPLE_PER_SEC = 2.2
const BATTERY_DRAIN_TRACTOR_PER_SEC = 16
const BATTERY_DRAIN_SCANNER_BASE_PER_SEC = 2.5
const BATTERY_DRAIN_SCANNER_PER_LEVEL = 2
const BATTERY_SCAN_PULSE_DRAIN_MULT = 1.35
const BATTERY_FUEL_PER_PCT = 2
const BATTERY_RECHARGE_PCT_PER_SEC = 10
const SHIP_DESTRUCTION_MS = 2200

export {
  WORLD_SCALE,
  PLAYER_MAX_SPEED,
  PLAYER_ROT_SPEED,
  GRAPPLE_SPEED,
  GRAPPLE_COOLDOWN_MS,
  GRAPPLE_MAX_RANGE,
  GRAPPLE_PULL_SPEED,
  GRAPPLE_ATTACH_DISTANCE,
  GRAPPLE_SOFT_DOCK_SPEED_MAX,
  GRAPPLE_DOCK_ASSIST_RADIUS,
  GRAPPLE_DOCK_DAMP_RATE,
  GRAPPLE_DOCK_STEER_ACCEL,
  GRAPPLE_RIDE_MIN_DAMAGE_SCALE,
  GRAPPLE_SOFT_COLLISION_SMOOTHING,
  ATTACH_RELEASE_REVERSE_BOOST,
  GRAPPLE_DETACH_GRACE_MS,
  PLAYER_FUEL_MAX_DEFAULT,
  FUEL_BURN_PER_SEC,
  FUEL_LOW_THRESHOLD,
  FUEL_LOST_GRACE_MS,
  FUEL_RESCUE_MIN_CLOSURE_SPEED,
  FUEL_RESCUE_FULL_PAUSE_CLOSURE_SPEED,
  FUEL_RESCUE_GRACE_DECAY_MIN,
  EMERGENCY_THRUST_MULT,
  BATTERY_DRAIN_EMERGENCY_THRUST_PER_SEC,
  DISTRESS_TOW_STEER_ACCEL,
  DISTRESS_TOW_DAMP_RATE,
  BATTERY_LOW_THRESHOLD,
  BATTERY_DRAIN_GRAPPLE_PER_SEC,
  BATTERY_DRAIN_TRACTOR_PER_SEC,
  BATTERY_DRAIN_SCANNER_BASE_PER_SEC,
  BATTERY_DRAIN_SCANNER_PER_LEVEL,
  BATTERY_SCAN_PULSE_DRAIN_MULT,
  BATTERY_FUEL_PER_PCT,
  BATTERY_RECHARGE_PCT_PER_SEC,
  SHIP_DESTRUCTION_MS
}
