const SPACE_BG_COLOR = 0x05070d
const SPACE_ACCENT_COLOR = 0xdee3e7
const GAMEPAD_DEAD_ZONE = 0.35
const GAMEPAD_MENU_REPEAT_MS = 180

export {
  SPACE_BG_COLOR,
  SPACE_ACCENT_COLOR,
  GAMEPAD_DEAD_ZONE,
  GAMEPAD_MENU_REPEAT_MS
}
