const TRACTOR_BEAM_MAX_LEVEL = 5
const TRACTOR_BEAM_RANGE_BY_LEVEL = [0, 230, 310, 395, 480, 570]
const TRACTOR_BEAM_PULL_BY_LEVEL = [0, 165, 225, 290, 355, 420]
const TRACTOR_BEAM_CONE_RADIANS = Math.PI / 3.5
const TRACTOR_HOLD_PADDING = 18
const TRACTOR_HOLD_FORWARD_PADDING = 14
const TRACTOR_HOLD_SURFACE_GAP = 6
const TRACTOR_COLLECT_SURFACE_GAP = 2
const TRACTOR_HOLD_SPRING_MULT = 0.45
const TRACTOR_VELOCITY_MATCH_RATE = 10
const TRACTOR_COLLECT_PULL_MULT = 2.45
const TRACTOR_COLLECT_SIZE_PULL_MAX = 2.35
const TRACTOR_COLLECT_SIZE_PULL_MIN = 1.45
const TRACTOR_COLLECT_FALLOFF_FLOOR = 0.38
const TRACTOR_HOLD_DAMP_MULT = 2.8
const TRACTOR_HOLD_REMOTE_DAMP_PER_SEC = 2.4
const TRACTOR_SPIN_DAMP_PER_SEC = 2.2
const TRACTOR_THRUST_TRANSFER = 0.72
const SCANNER_MAX_LEVEL = 5
const SCANNER_RANGE_BY_LEVEL = [0, 420, 620, 820, 1020, 1280]
const SCANNER_HOLD_MS = 2000
const SCANNER_PULSE_MS = 700
const CHARGE_FUSE_MS = 5000
const CHARGE_BLAST_RADIUS = 130
const CHARGE_BLAST_DAMAGE_MAX = 38
const CHARGE_BLAST_DAMAGE_MIN = 10
const NANOBOT_MAX_LEVEL = 5
const NANOBOT_BATTERY_DRAIN_BASE_PER_SEC = 22
const NANOBOT_BATTERY_DRAIN_PER_LEVEL = 5
const NANOBOT_REPAIR_HP_PER_SEC_BASE = 1.8
const NANOBOT_REPAIR_HP_PER_LEVEL = 1.4
const CAPACITY_UPGRADE_MAX_LEVEL = 5
const FUEL_CAPACITY_BONUS_PER_LEVEL = 100
const BATTERY_CAPACITY_BONUS_PER_LEVEL = 20
const CARGO_HOLD_BONUS_PER_LEVEL = 15
const DRILL_SPEED_REDUCTION_PER_LEVEL = 0.1
const DRILL_SPEED_MIN_MULT = 0.5
const SUPERCAPACITOR_MAX_LEVEL = 5
const SUPERCAPACITOR_FUEL_REDUCTION_PER_LEVEL = 0.12
const SUPERCAPACITOR_FUEL_MULT_MIN = 0.4
const GRAPPLE_UPGRADE_MAX_LEVEL = 5
const GRAPPLE_RANGE_BY_LEVEL = [360, 405, 450, 495, 540, 585]
const GRAPPLE_PULL_BY_LEVEL = [300, 335, 370, 405, 440, 475]
const GRAPPLE_HOOK_SPEED_BY_LEVEL = [460, 495, 530, 565, 600, 635]
const GRAPPLE_COOLDOWN_MS_BY_LEVEL = [350, 325, 300, 275, 250, 225]
const GRAPPLE_BATTERY_DRAIN_REDUCTION_PER_LEVEL = 0.05
const GRAPPLE_BATTERY_DRAIN_MULT_MIN = 0.75
const DRILL_YIELD_UNITS_BONUS_PER_LEVEL = 0.2

export {
  TRACTOR_BEAM_MAX_LEVEL,
  TRACTOR_BEAM_RANGE_BY_LEVEL,
  TRACTOR_BEAM_PULL_BY_LEVEL,
  TRACTOR_BEAM_CONE_RADIANS,
  TRACTOR_HOLD_PADDING,
  TRACTOR_HOLD_FORWARD_PADDING,
  TRACTOR_HOLD_SURFACE_GAP,
  TRACTOR_COLLECT_SURFACE_GAP,
  TRACTOR_HOLD_SPRING_MULT,
  TRACTOR_VELOCITY_MATCH_RATE,
  TRACTOR_COLLECT_PULL_MULT,
  TRACTOR_COLLECT_SIZE_PULL_MAX,
  TRACTOR_COLLECT_SIZE_PULL_MIN,
  TRACTOR_COLLECT_FALLOFF_FLOOR,
  TRACTOR_HOLD_DAMP_MULT,
  TRACTOR_HOLD_REMOTE_DAMP_PER_SEC,
  TRACTOR_SPIN_DAMP_PER_SEC,
  TRACTOR_THRUST_TRANSFER,
  SCANNER_MAX_LEVEL,
  SCANNER_RANGE_BY_LEVEL,
  SCANNER_HOLD_MS,
  SCANNER_PULSE_MS,
  CHARGE_FUSE_MS,
  CHARGE_BLAST_RADIUS,
  CHARGE_BLAST_DAMAGE_MAX,
  CHARGE_BLAST_DAMAGE_MIN,
  NANOBOT_MAX_LEVEL,
  NANOBOT_BATTERY_DRAIN_BASE_PER_SEC,
  NANOBOT_BATTERY_DRAIN_PER_LEVEL,
  NANOBOT_REPAIR_HP_PER_SEC_BASE,
  NANOBOT_REPAIR_HP_PER_LEVEL,
  CAPACITY_UPGRADE_MAX_LEVEL,
  FUEL_CAPACITY_BONUS_PER_LEVEL,
  BATTERY_CAPACITY_BONUS_PER_LEVEL,
  CARGO_HOLD_BONUS_PER_LEVEL,
  DRILL_SPEED_REDUCTION_PER_LEVEL,
  DRILL_SPEED_MIN_MULT,
  SUPERCAPACITOR_MAX_LEVEL,
  SUPERCAPACITOR_FUEL_REDUCTION_PER_LEVEL,
  SUPERCAPACITOR_FUEL_MULT_MIN,
  GRAPPLE_UPGRADE_MAX_LEVEL,
  GRAPPLE_RANGE_BY_LEVEL,
  GRAPPLE_PULL_BY_LEVEL,
  GRAPPLE_HOOK_SPEED_BY_LEVEL,
  GRAPPLE_COOLDOWN_MS_BY_LEVEL,
  GRAPPLE_BATTERY_DRAIN_REDUCTION_PER_LEVEL,
  GRAPPLE_BATTERY_DRAIN_MULT_MIN,
  DRILL_YIELD_UNITS_BONUS_PER_LEVEL
}
