const SHIP_UNDOCK_TRANSITION_MS = 900
const SHIP_DOCK_APPROACH_MS = 650
const SHIP_DOCK_EXIT_MS = 850
const SHIP_TRANSITION_LAUNCH_DISTANCE = 160
const MOTHERSHIP_APPROACH_X = -120

export {
  SHIP_UNDOCK_TRANSITION_MS,
  SHIP_DOCK_APPROACH_MS,
  SHIP_DOCK_EXIT_MS,
  SHIP_TRANSITION_LAUNCH_DISTANCE,
  MOTHERSHIP_APPROACH_X
}
